const requirePath = name => (
  require(`./svgs/${name}.svg`)
)

export default {
  'Accepts Credit Card Payments': requirePath('credit_card'),
  'Accepts Credit Cards': requirePath('credit_card'),
  'Accepts Electronic Payments': requirePath('credit_card'),
  'Air Conditioning': requirePath('air_conditioning'),
  Alarm: requirePath('alarm'),
  'All Bills Paid': requirePath('corporate_billing'),
  'All Paid Utilies': requirePath('paid_utilities'),
  Amenity: requirePath('amenity'),
  'Assisted Living': requirePath('assisted_living'),
  Balcony: requirePath('balcony'),
  'Basketball Court(s)': requirePath('basketball'),
  'Business Center': requirePath('business_conference_center'),
  'Cable Ready': requirePath('cable_ready'),
  'Campus Shuttle': requirePath('campus_shuttle'),
  'Car Port': requirePath('car_garage_parking'),
  'Cats OK': requirePath('cats_ok'),
  'Ceiling Fan': requirePath('ceiling_fan'),
  'Ceiling Fan(s)': requirePath('ceiling_fan'),
  'Central Air': requirePath('air_conditioning'),
  'Ceramic Tiles': requirePath('ceramic_tiles'),
  Clubhouse: requirePath('clubhouse_recreation'),
  'Conference Room': requirePath('business_conference_center'),
  'Controlled Access': requirePath('gated_controlled_access'),
  'Corporate Billing Available': requirePath('corporate_billing'),
  'Covered Parking': requirePath('car_garage_parking'),
  'Disability Access': requirePath('disability_access'),
  Deck: requirePath('deck_hardwood'),
  'Dining Room': requirePath('dining_room'),
  Dishwasher: requirePath('dishwasher'),
  'Dogs OK': requirePath('dogs_ok'),
  'Door Attendant': requirePath('door_attendant'),
  Elevator: requirePath('elevator'),
  'Emergency Maintenance': requirePath('emergency_maintenance'),
  'Extra Storage': requirePath('extra_storage'),
  'Finished Basement': requirePath('finished_basement'),
  Fireplace: requirePath('fireplace'),
  'Fitness Center': requirePath('fitness_center'),
  'Full Concierge Service': requirePath('full_concierge'),
  Furnished: requirePath('furnished'),
  'Furnished Apartments': requirePath('furnished'),
  Garage: requirePath('car_garage_parking'),
  'Garbage Disposal': requirePath('garbage_disposal'),
  'Garden Tub': requirePath('hot_tub_spa'),
  'Gas Range': requirePath('gas_range'),
  'Gated Access': requirePath('gated_controlled_access'),
  'Green Community': requirePath('green_community'),
  'Hardwood Flooring': requirePath('deck_hardwood'),
  Heat: requirePath('heat'),
  'High Speed Internet Access': requirePath('wifi_high_speed_internet'),
  'Hot Tub': requirePath('hot_tub_spa'),
  'Housekeeping Available': requirePath('housekeeping'),
  'Independent Living': requirePath('onsite_management'),
  'Individual Leases': requirePath('sublets'),
  'Internet Included': requirePath('wifi_high_speed_internet'),
  'Island Kitchens': requirePath('island_kitchens'),
  'Laundry Facility': requirePath('laundry'),
  'Living Room': requirePath('living_room'),
  'Loft Layout': requirePath('loft_vaulted_ceiling'),
  'Media Center': requirePath('cable_ready'),
  Microwave: requirePath('microwave'),
  'New/Renovated Interior': requirePath('loft_vaulted_ceiling'),
  'No Pets Allowed': requirePath('no_pets'),
  'On Site Maintenance': requirePath('onsite_maintenance'),
  'On Site Management': requirePath('onsite_management'),
  'On Site Patrol': requirePath('onsite_patrol'),
  'Oversized Closets': requirePath('oversized_closets'),
  Patio: requirePath('patio_yard'),
  'Pet Friendly': requirePath('pets'),
  'Pet Park': requirePath('pets'),
  Pets: requirePath('pets'),
  'Pets Allowed': requirePath('pets'),
  'Pets OK': requirePath('pets'),
  Playground: requirePath('playground'),
  'Private Yard': requirePath('patio_yard'),
  'Public Transit': requirePath('public_transit'),
  'Public Transportation': requirePath('public_transit'),
  'Racquetball Court(s)': requirePath('tennis_court'),
  'Recreation Room': requirePath('clubhouse_recreation'),
  Refrigerator: requirePath('refigerator_stainless_steel'),
  'Se Habla Espanol': requirePath('espanol'),
  'Short Term Available': requirePath('short_term'),
  'Short Term Lease': requirePath('short_term'),
  'Smoke Free': requirePath('smoke_free'),
  'Some Paid Utilities': requirePath('paid_utilities'),
  'Stainless Steel Appliances': requirePath('refigerator_stainless_steel'),
  'Sublets Allowed': requirePath('sublets'),
  Subsidies: requirePath('corporate_billing'),
  'Swimming Pool': requirePath('swimming_pool'),
  'Tennis Court(s)': requirePath('tennis_court'),
  Tiles: requirePath('ceramic_tiles'),
  'Trail, Bike, Hike, Jog': requirePath('trail_bike_hike'),
  'University Shuttle Service': requirePath('campus_shuttle'),
  'Vaulted Ceiling': requirePath('loft_vaulted_ceiling'),
  'Vaulted Ceilings': requirePath('loft_vaulted_ceiling'),
  View: requirePath('view'),
  'Washer & Dryer Connections': requirePath('laundry'),
  'Washer & Dryer In Unit': requirePath('laundry'),
  'Wireless Internet Access': requirePath('wifi_high_speed_internet'),
}
