// flow-typed signature: 689716e37ef3c77f1f8b4b6d1bb9e21e
// flow-typed version: <<STUB>>/react-input-range_v1.1.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-input-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-input-range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-input-range/lib/bundle/react-input-range' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/bundle/react-input-range.min' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/index' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/input-range/default-class-names' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/input-range/input-range' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/input-range/key-codes' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/input-range/label' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/input-range/range-prop-type' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/input-range/slider' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/input-range/track' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/input-range/value-prop-type' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/input-range/value-transformer' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/utils/captialize' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/utils/clamp' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/utils/distance-to' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/utils/index' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/utils/is-defined' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/utils/is-number' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/utils/is-object' {
  declare module.exports: any;
}

declare module 'react-input-range/lib/js/utils/length' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/index' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/input-range/default-class-names' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/input-range/input-range' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/input-range/key-codes' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/input-range/label' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/input-range/range-prop-type' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/input-range/slider' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/input-range/track' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/input-range/value-prop-type' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/input-range/value-transformer' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/utils/captialize' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/utils/clamp' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/utils/distance-to' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/utils/index' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/utils/is-defined' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/utils/is-number' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/utils/is-object' {
  declare module.exports: any;
}

declare module 'react-input-range/src/js/utils/length' {
  declare module.exports: any;
}

declare module 'react-input-range/webpack-example.config.babel' {
  declare module.exports: any;
}

declare module 'react-input-range/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-input-range/lib/bundle/react-input-range.js' {
  declare module.exports: $Exports<'react-input-range/lib/bundle/react-input-range'>;
}
declare module 'react-input-range/lib/bundle/react-input-range.min.js' {
  declare module.exports: $Exports<'react-input-range/lib/bundle/react-input-range.min'>;
}
declare module 'react-input-range/lib/js/index.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/index'>;
}
declare module 'react-input-range/lib/js/input-range/default-class-names.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/input-range/default-class-names'>;
}
declare module 'react-input-range/lib/js/input-range/input-range.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/input-range/input-range'>;
}
declare module 'react-input-range/lib/js/input-range/key-codes.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/input-range/key-codes'>;
}
declare module 'react-input-range/lib/js/input-range/label.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/input-range/label'>;
}
declare module 'react-input-range/lib/js/input-range/range-prop-type.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/input-range/range-prop-type'>;
}
declare module 'react-input-range/lib/js/input-range/slider.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/input-range/slider'>;
}
declare module 'react-input-range/lib/js/input-range/track.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/input-range/track'>;
}
declare module 'react-input-range/lib/js/input-range/value-prop-type.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/input-range/value-prop-type'>;
}
declare module 'react-input-range/lib/js/input-range/value-transformer.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/input-range/value-transformer'>;
}
declare module 'react-input-range/lib/js/utils/captialize.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/utils/captialize'>;
}
declare module 'react-input-range/lib/js/utils/clamp.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/utils/clamp'>;
}
declare module 'react-input-range/lib/js/utils/distance-to.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/utils/distance-to'>;
}
declare module 'react-input-range/lib/js/utils/index.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/utils/index'>;
}
declare module 'react-input-range/lib/js/utils/is-defined.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/utils/is-defined'>;
}
declare module 'react-input-range/lib/js/utils/is-number.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/utils/is-number'>;
}
declare module 'react-input-range/lib/js/utils/is-object.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/utils/is-object'>;
}
declare module 'react-input-range/lib/js/utils/length.js' {
  declare module.exports: $Exports<'react-input-range/lib/js/utils/length'>;
}
declare module 'react-input-range/src/js/index.js' {
  declare module.exports: $Exports<'react-input-range/src/js/index'>;
}
declare module 'react-input-range/src/js/input-range/default-class-names.js' {
  declare module.exports: $Exports<'react-input-range/src/js/input-range/default-class-names'>;
}
declare module 'react-input-range/src/js/input-range/input-range.jsx' {
  declare module.exports: $Exports<'react-input-range/src/js/input-range/input-range'>;
}
declare module 'react-input-range/src/js/input-range/key-codes.js' {
  declare module.exports: $Exports<'react-input-range/src/js/input-range/key-codes'>;
}
declare module 'react-input-range/src/js/input-range/label.jsx' {
  declare module.exports: $Exports<'react-input-range/src/js/input-range/label'>;
}
declare module 'react-input-range/src/js/input-range/range-prop-type.js' {
  declare module.exports: $Exports<'react-input-range/src/js/input-range/range-prop-type'>;
}
declare module 'react-input-range/src/js/input-range/slider.jsx' {
  declare module.exports: $Exports<'react-input-range/src/js/input-range/slider'>;
}
declare module 'react-input-range/src/js/input-range/track.jsx' {
  declare module.exports: $Exports<'react-input-range/src/js/input-range/track'>;
}
declare module 'react-input-range/src/js/input-range/value-prop-type.js' {
  declare module.exports: $Exports<'react-input-range/src/js/input-range/value-prop-type'>;
}
declare module 'react-input-range/src/js/input-range/value-transformer.js' {
  declare module.exports: $Exports<'react-input-range/src/js/input-range/value-transformer'>;
}
declare module 'react-input-range/src/js/utils/captialize.js' {
  declare module.exports: $Exports<'react-input-range/src/js/utils/captialize'>;
}
declare module 'react-input-range/src/js/utils/clamp.js' {
  declare module.exports: $Exports<'react-input-range/src/js/utils/clamp'>;
}
declare module 'react-input-range/src/js/utils/distance-to.js' {
  declare module.exports: $Exports<'react-input-range/src/js/utils/distance-to'>;
}
declare module 'react-input-range/src/js/utils/index.js' {
  declare module.exports: $Exports<'react-input-range/src/js/utils/index'>;
}
declare module 'react-input-range/src/js/utils/is-defined.js' {
  declare module.exports: $Exports<'react-input-range/src/js/utils/is-defined'>;
}
declare module 'react-input-range/src/js/utils/is-number.js' {
  declare module.exports: $Exports<'react-input-range/src/js/utils/is-number'>;
}
declare module 'react-input-range/src/js/utils/is-object.js' {
  declare module.exports: $Exports<'react-input-range/src/js/utils/is-object'>;
}
declare module 'react-input-range/src/js/utils/length.js' {
  declare module.exports: $Exports<'react-input-range/src/js/utils/length'>;
}
declare module 'react-input-range/webpack-example.config.babel.js' {
  declare module.exports: $Exports<'react-input-range/webpack-example.config.babel'>;
}
declare module 'react-input-range/webpack.config.babel.js' {
  declare module.exports: $Exports<'react-input-range/webpack.config.babel'>;
}
