// flow-typed signature: 1e50f8fbd68cc5835a3f467ea280b43f
// flow-typed version: <<STUB>>/react-themed_v3.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-themed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-themed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-themed/dist/react-themed' {
  declare module.exports: any;
}

declare module 'react-themed/dist/react-themed.min' {
  declare module.exports: any;
}

declare module 'react-themed/es/compose' {
  declare module.exports: any;
}

declare module 'react-themed/es/const' {
  declare module.exports: any;
}

declare module 'react-themed/es/expand' {
  declare module.exports: any;
}

declare module 'react-themed/es/index' {
  declare module.exports: any;
}

declare module 'react-themed/es/themeContext' {
  declare module.exports: any;
}

declare module 'react-themed/es/themed' {
  declare module.exports: any;
}

declare module 'react-themed/es/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-themed/lib/compose' {
  declare module.exports: any;
}

declare module 'react-themed/lib/const' {
  declare module.exports: any;
}

declare module 'react-themed/lib/expand' {
  declare module.exports: any;
}

declare module 'react-themed/lib/index' {
  declare module.exports: any;
}

declare module 'react-themed/lib/themeContext' {
  declare module.exports: any;
}

declare module 'react-themed/lib/themed' {
  declare module.exports: any;
}

declare module 'react-themed/lib/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-themed/src/compose-test' {
  declare module.exports: any;
}

declare module 'react-themed/src/compose' {
  declare module.exports: any;
}

declare module 'react-themed/src/const' {
  declare module.exports: any;
}

declare module 'react-themed/src/expand-test' {
  declare module.exports: any;
}

declare module 'react-themed/src/expand' {
  declare module.exports: any;
}

declare module 'react-themed/src/index' {
  declare module.exports: any;
}

declare module 'react-themed/src/themeContext-test' {
  declare module.exports: any;
}

declare module 'react-themed/src/themeContext' {
  declare module.exports: any;
}

declare module 'react-themed/src/themed-test' {
  declare module.exports: any;
}

declare module 'react-themed/src/themed' {
  declare module.exports: any;
}

declare module 'react-themed/src/ThemeProvider-test' {
  declare module.exports: any;
}

declare module 'react-themed/src/ThemeProvider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-themed/dist/react-themed.js' {
  declare module.exports: $Exports<'react-themed/dist/react-themed'>;
}
declare module 'react-themed/dist/react-themed.min.js' {
  declare module.exports: $Exports<'react-themed/dist/react-themed.min'>;
}
declare module 'react-themed/es/compose.js' {
  declare module.exports: $Exports<'react-themed/es/compose'>;
}
declare module 'react-themed/es/const.js' {
  declare module.exports: $Exports<'react-themed/es/const'>;
}
declare module 'react-themed/es/expand.js' {
  declare module.exports: $Exports<'react-themed/es/expand'>;
}
declare module 'react-themed/es/index.js' {
  declare module.exports: $Exports<'react-themed/es/index'>;
}
declare module 'react-themed/es/themeContext.js' {
  declare module.exports: $Exports<'react-themed/es/themeContext'>;
}
declare module 'react-themed/es/themed.js' {
  declare module.exports: $Exports<'react-themed/es/themed'>;
}
declare module 'react-themed/es/ThemeProvider.js' {
  declare module.exports: $Exports<'react-themed/es/ThemeProvider'>;
}
declare module 'react-themed/lib/compose.js' {
  declare module.exports: $Exports<'react-themed/lib/compose'>;
}
declare module 'react-themed/lib/const.js' {
  declare module.exports: $Exports<'react-themed/lib/const'>;
}
declare module 'react-themed/lib/expand.js' {
  declare module.exports: $Exports<'react-themed/lib/expand'>;
}
declare module 'react-themed/lib/index.js' {
  declare module.exports: $Exports<'react-themed/lib/index'>;
}
declare module 'react-themed/lib/themeContext.js' {
  declare module.exports: $Exports<'react-themed/lib/themeContext'>;
}
declare module 'react-themed/lib/themed.js' {
  declare module.exports: $Exports<'react-themed/lib/themed'>;
}
declare module 'react-themed/lib/ThemeProvider.js' {
  declare module.exports: $Exports<'react-themed/lib/ThemeProvider'>;
}
declare module 'react-themed/src/compose-test.js' {
  declare module.exports: $Exports<'react-themed/src/compose-test'>;
}
declare module 'react-themed/src/compose.js' {
  declare module.exports: $Exports<'react-themed/src/compose'>;
}
declare module 'react-themed/src/const.js' {
  declare module.exports: $Exports<'react-themed/src/const'>;
}
declare module 'react-themed/src/expand-test.js' {
  declare module.exports: $Exports<'react-themed/src/expand-test'>;
}
declare module 'react-themed/src/expand.js' {
  declare module.exports: $Exports<'react-themed/src/expand'>;
}
declare module 'react-themed/src/index.js' {
  declare module.exports: $Exports<'react-themed/src/index'>;
}
declare module 'react-themed/src/themeContext-test.js' {
  declare module.exports: $Exports<'react-themed/src/themeContext-test'>;
}
declare module 'react-themed/src/themeContext.js' {
  declare module.exports: $Exports<'react-themed/src/themeContext'>;
}
declare module 'react-themed/src/themed-test.js' {
  declare module.exports: $Exports<'react-themed/src/themed-test'>;
}
declare module 'react-themed/src/themed.js' {
  declare module.exports: $Exports<'react-themed/src/themed'>;
}
declare module 'react-themed/src/ThemeProvider-test.js' {
  declare module.exports: $Exports<'react-themed/src/ThemeProvider-test'>;
}
declare module 'react-themed/src/ThemeProvider.js' {
  declare module.exports: $Exports<'react-themed/src/ThemeProvider'>;
}
