#!/bin/sh
set -e

cd "$(dirname "$0")/.."

REPO="rentpath/react-ui"
# Using HEAD~1 because Jenkins creates a merge commit
GIT_COMMIT=`git rev-parse HEAD~1`
COMMITISH=${GIT_COMMIT:0:7};
DATE=`date -u "+%Y%m%d"`;
VERSION="$DATE-$BUILD_NUMBER-$COMMITISH";

# Pass variables needed to generate BUILD-INFO
docker build \
      -f ./Dockerfile \
      -t rentpath/react-ui:$VERSION \
      "$@" .

docker push rentpath/react-ui:$VERSION
