export MyGreatNewComponent from './components/MyGreatNewComponent'
export MyGreatNewComponentContainer from './container'
export MyGreatNewComponentSelector from './selectors/selector'
export reducer from './reducer'
export { genericAction } from './actions'
export { GENERIC_CONST } from './const'
