// flow-typed signature: a137d1bccb9d876def54c58cc5b6e8c1
// flow-typed version: <<STUB>>/@rentpath/react-ui-utils_v0.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rentpath/react-ui-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rentpath/react-ui-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rentpath/react-ui-utils/lib/composeProps' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/lib/index' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/lib/keyMirror' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/lib/parseArgs' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/lib/randomId' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/src/__tests__/composeProps-test' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/src/__tests__/keyMirror-test' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/src/__tests__/parseArgs-test' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/src/__tests__/randomId-test' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/src/composeProps' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/src/index' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/src/keyMirror' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/src/parseArgs' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/src/randomId' {
  declare module.exports: any;
}

declare module '@rentpath/react-ui-utils/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rentpath/react-ui-utils/lib/composeProps.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/lib/composeProps'>;
}
declare module '@rentpath/react-ui-utils/lib/index.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/lib/index'>;
}
declare module '@rentpath/react-ui-utils/lib/keyMirror.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/lib/keyMirror'>;
}
declare module '@rentpath/react-ui-utils/lib/parseArgs.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/lib/parseArgs'>;
}
declare module '@rentpath/react-ui-utils/lib/randomId.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/lib/randomId'>;
}
declare module '@rentpath/react-ui-utils/src/__tests__/composeProps-test.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/src/__tests__/composeProps-test'>;
}
declare module '@rentpath/react-ui-utils/src/__tests__/keyMirror-test.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/src/__tests__/keyMirror-test'>;
}
declare module '@rentpath/react-ui-utils/src/__tests__/parseArgs-test.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/src/__tests__/parseArgs-test'>;
}
declare module '@rentpath/react-ui-utils/src/__tests__/randomId-test.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/src/__tests__/randomId-test'>;
}
declare module '@rentpath/react-ui-utils/src/composeProps.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/src/composeProps'>;
}
declare module '@rentpath/react-ui-utils/src/index.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/src/index'>;
}
declare module '@rentpath/react-ui-utils/src/keyMirror.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/src/keyMirror'>;
}
declare module '@rentpath/react-ui-utils/src/parseArgs.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/src/parseArgs'>;
}
declare module '@rentpath/react-ui-utils/src/randomId.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/src/randomId'>;
}
declare module '@rentpath/react-ui-utils/test/setup.js' {
  declare module.exports: $Exports<'@rentpath/react-ui-utils/test/setup'>;
}
