name: lint
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: check out latest commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
          token: ${{ github.token }}

      - name: cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: node_modules/
          key: reactui-modules-${{ hashFiles('yarn.lock') }}

      - name: get node version
        id: node-version
        run: echo "::set-output name=value::$( cat .node-version )"

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.value }}
          registry-url: https://npm.pkg.github.com
          scope: '@rentpath'

      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache dependencies
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_GPR_TOKEN }}
        run: |
          yarn config set @rentpath:registry https://npm.pkg.github.com
          yarn --frozen-lockfile --production=false

      - name: lint
        run: yarn run lint:js
