name: test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: check out latest commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}
          token: ${{ github.token }}

      - name: cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules/
          key: reactui-modules-${{ hashFiles('yarn.lock') }}

      - name: get node version
        id: node-version
        run: echo "::set-output name=value::$( cat .node-version )"

      - name: set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node-version.outputs.value }}
          registry-url: https://npm.pkg.github.com
          scope: "@rentpath"

      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache dependencies
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
        run: |
          yarn config set @rentpath:registry https://npm.pkg.github.com
          yarn --frozen-lockfile --production=false

      - name: unit tests
        run: |
          yarn run test --maxWorkers=2

      # enable as soon as coveralls is working
      # or move to its own job?
      # - name: test code coverage
      #   run: |
      #     yarn run report-coverage
